### ISSUE TITLE
Issue with Player Class

### ISSUE THREAD

**Issue by J0S349** [JoeM88/RockPaperScissors-Game#1]
So when it comes to running the RockPaperScissors.java file, it implements the abstract class Player.java. Within this class, it calls a function within Player, which is .setChoice(int), but it is never implemented. Might want to fix that as soon as possible. 
Thank You, 
~ Peeps

**Comment by JoeM88** [comment]
Thank you for noticing this issue Jose. I have taken the time to correct this issue.
